## our React TodoMVC app is written
## in node so thats what we select.
## Cypress is agnostic to your apps
## backend language though.
language: node_js

node_js:
  - 9

install:
  - yarn

script:
  - yarn run test

