## our React TodoMVC app is written
## in node so thats what we select.
## Cypress is agnostic to your apps
## backend language though.
language: node_js

node_js:
  - 9

## Cache folders with installed NPM modules
## to avoid downloading Cypress again and again
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn run test

